site_name: NEWAGE Quality System Documentation
nav:
    - Quality System Manual (QSM): index.md
    - Quality System Procedures (QSPs): QSPs/index.md
    - Standard Operating Procedures (SOPs): SOPs/index.md
theme: readthedocs
